### ISSUE TITLE
Fullscreen not working properly inside paper-scroll-header-panel (maybe working?)

### ISSUE THREAD

**Issue by alefwmm** [PolymerElements/paper-scroll-header-panel#2]
As I see you are doing a replacement of core-scroll-header-panel. I had an issue with it, and I'd like to know if this version solves that problem. I saw in the CSS code that it is still using **translateZ(0)** code for performance improvements.

The old problem link: [https://github.com/Polymer/core-scroll-header-panel/issues/46]

Thanks, and I am sorry for replicating the same issue.

**Comment by blasten** [comment]
You can disable it via the css selector:

``` css
paper-scroll-header-panel::shadow #mainContainer {
  -webkit-transform: none;
  transform: none;
}
```
