### ISSUE TITLE
Set background-image leads to an error in the URL

### ISSUE THREAD

**Issue by steinhoff1989** [PolymerElements/paper-scroll-header-panel#4]
Hi,

I just can't set an background image to the toolbar by using the mixin definition like:

``` css
:host{
    --paper-scroll-header-panel-full-header: {
        background-image: url(http://lorempixel.com/900/200/nature);
    };
}
```

The referenced image-URL is becoming something like this and leads to a error:
"http://localhost:63342/www/%20%20//lorempixel.com/900/200/nature"

However it works when I define the CSS like the following. (What is not my prefered solution):

``` css
:host{
    --paper-scroll-header-panel-full-header: 
        background-image: url(http://lorempixel.com/900/200/nature);
}
```

Is there a possibility to set the background image by using the normal property object to define more than just the background inside the "--paper-scroll-header-panel-full-header" mixin?

Thank's
